# Adapted from https://code.haxe.org/category/other/deploy-to-haxelib-using-travis-and-github-releases.html

sudo: required
dist: trusty

language: haxe

haxe:
 - "3.4.7"
 - "4.0.0-rc.2"
 - "development"

install:
 - haxelib dev hxmath .
 - haxelib install hxcpp
 - haxelib install nanotest

script:
 - haxe test_cpp.hxml
 - haxe test_neko.hxml